version: "3.8"

services:
  backend:
    container_name: backend-container
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/backend
    ports:
      - 8080:8080
    env_file:
      - .env