version: "3.8"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      target: development
    volumes:
      - .:/backend
    ports:
      - 8080:8080
    env_file:
      - .env