version: "3.8"

services:
  backend:
    container_name: backend-dev
    image: backend-dev
    build:
      context: .
      target: development
    volumes:
      - .:/backend
    ports:
      - 8080:8080